baseURL = "https://moreban.github.io/azt"

languageCode = "zh-CN"
theme        = "hugo-book"
title        = "Azt-Go Docs"

hasCJKLanguage = true
metaDataFormat = "yaml"

defaultContentLanguage               = "zh"
defaultContentLanguageInSubdir       = true
enableMissingTranslationPlaceholders = false

# For hugo-book

# (Optional) Set Google Analytics if you use it to track your website.
# Always put it on the top of the configuration file, otherwise it won't work
googleAnalytics = "UA-XXXXXXXXX-X"

# (Optional) If you provide a Disqus shortname, comments will be enabled on
# all pages.
# disqusShortname = "my-site"

# (Optional) Set this to true if you use capital letters in file names
disablePathToLower = true

# (Optional) Set this to true to enable 'Last Modified by' date and git author
#  information on 'doc' type pages.
enableGitInfo = true

# (Optional) Theme is intended for documentation use, therefore it doesn't render taxonomy.
# You can remove related files with config below
disableKinds = ['taxonomy', 'taxonomyTerm']

[params]
    BookTheme = 'dark'

    # (Optional, default true) Controls table of contents visibility on right side of pages.
    # Start and end levels can be controlled with markup.tableOfContents setting.
    # You can also specify this parameter per page in front matter.
    BookToC = true

    # (Optional, default none) Set the path to a logo for the book. If the logo is
    # /static/logo.png then the path would be 'logo.png'
    # BookLogo = 'images/og-image.png'

    # (Optional, default docs) Specify section of content to render as menu
    # You can also set value to "*" to render all sections to menu
    BookSection = '*' # 'Azt Docs'

    # Set source repository location.
    # Used for 'Last Modified' and 'Edit this page' links.
    BookRepo = 'https://github.com/moreban/azt'

    # Specifies commit portion of the link to the page's last modified commit hash for 'doc' page
    # type.
    # Required if 'BookRepo' param is set.
    # Value used to construct a URL consisting of BookRepo/BookCommitPath/<commit-hash>
    # Github uses 'commit', Bitbucket uses 'commits'
    BookCommitPath = 'commit'

    # Enable 'Edit this page' links for 'doc' page type.
    # Disabled by default. Uncomment to enable. Requires 'BookRepo' param.
    # Path must point to the site directory.
    BookEditPath = 'edit/master/docs'

    # (Optional, default January 2, 2006) Configure the date format used on the pages
    # - In git information
    # - In blog posts
    BookDateFormat = 'Jan 2, 2006'

    # (Optional, default true) Enables search function with flexsearch,
    # Index is built on fly, therefore it might slowdown your website.
    # Configuration for indexing can be adjusted in i18n folder per language.
    BookSearch = true

    # (Optional, default true) Enables comments template on pages
    # By default partials/docs/comments.html includes Disqus template
    # See https://gohugo.io/content-management/comments/#configure-disqus
    # Can be overwritten by same param in page frontmatter
    BookComments = true

    # /!\ This is an experimental feature, might be removed or changed at any time
    # (Optional, experimental, default false) Enables portable links and link checks in markdown pages.
    # Portable links meant to work with text editors and let you write markdown without {{< relref >}} shortcode
    # Theme will print warning if page referenced in markdown does not exists.
    BookPortableLinks = true

    # /!\ This is an experimental feature, might be removed or changed at any time
    # (Optional, experimental, default false) Enables service worker that caches visited pages and resources for offline use.
    BookServiceWorker = true


    # For hugo-theme-techdoc

    # Source Code repository section
    description       = "An code generation maintain tool."
    github_repository = "https://github.com/moreban/azt"

    # Documentation repository section
    # documentation repository (set edit link to documentation repository)
    github_doc_repository = "https://github.com/moreban/azt/docs"

    # Analytic section
    google_analytics_id      = "" # Your Google Analytics tracking id
    google_site_verification = "" # Your Google Site Verification for Search Console
    tag_manager_container_id = "" # Your Google Tag Manager container id

    # Open Graph and Twitter Cards settings section
    # Open Graph settings for each page are set on the front matter.
    # See https://gohugo.io/templates/internal/#open-graph
    # See https://gohugo.io/templates/internal/#twitter-cards
    images = ["images/og-image.png"] # Open graph images are placed in `static/images`
    title  = "Azt-Go Docs"

    # Theme settings section
    # Theme color
    # See color value reference https://developer.mozilla.org/en-US/docs/Web/CSS/color
    custom_background_color = ""
    custom_font_color       = ""

    # Documentation Menu section
    # Menu style settings
    menu_style = "open-menu" # "open-menu" or "slide-menu"

    # Date format
    dateformat = "" # default "2 Jan 2006"
    # See the format reference https://gohugo.io/functions/format/#hugo-date-and-time-templating-reference

    # path name excluded from documentation menu
    menu_exclusion = ["archive", "archives", "blog", "entry", "post", "posts"]

    # Algolia site search section
    # See https://www.algolia.com/doc/
    algolia_apiKey        = "cbf12a63ff72d9c5dc0c10c195cf9128" # Search-Only API Key
    algolia_appId         = "7W4SAN4PLK"
    algolia_indexName     = "hugo-demo-techdoc"
    algolia_search_enable = true

# Global menu section
# See https://gohugo.io/content-management/menus/
[menu]
[[menu.main]]
    name   = "Home"
    url    = "/"
    weight = 1

[[menu.main]]
    name   = "GitHub"
    url    = "https://github.com/moreban"
    weight = 2

# Markup configure section
# See https://gohugo.io/getting-started/configuration-markup/
[markup]
    defaultMarkdownHandler = "goldmark"
[markup.goldmark.renderer]
    unsafe = true
[markup.tableOfContents]
    endLevel   = 4
    ordered    = false
    startLevel = 2

# Algolia Search configure section
[outputFormats.Algolia]
    baseName       = "algolia"
    isPlainText    = true
    mediaType      = "application/json"
    notAlternative = true

[params.algolia]
    params = ["categories", "tags"]
    vars = [
        "content",
        "date",
        "description",
        "keywords",
        "lastmod",
        "permalink",
        "publishdate",
        "summary",
        "title",
    ]
