on:
  push:
    tags:
      - "v*.*.*"
name: release-build
jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      discussions: write
    # permissions: write-all # this is the FIX
    steps:
      - name: Install Go
        uses: actions/setup-go@v5
        with:
          go-version: ^1.23.1

      - name: Checkout code
        uses: actions/checkout@v4

      - name: Checkout tag
        run: |
          git fetch --depth=1 origin +refs/tags/*:refs/tags/*
          tag_name="${GITHUB_REF##*/}"
          echo Tag $tag_name
          git checkout $tag_name
          echo "TAG_NAME=${tag_name}" >> $GITHUB_ENV

      - name: Build
        run: |
          make V=1 release -j$(nproc)

      # # This step reads a file from repo and use it for body of the release
      # # This works on any self-hosted runner OS
      # - name: Read release.md and use it as a body of new release
      #   id: read_release
      #   shell: bash
      #   run: |
      #     RELEASE_VERSION=${GITHUB_REF#refs/*/}
      #     VERSION=${RELEASE_VERSION/v/}
      #     # echo "RELEASE_VERSION=${RELEASE_VERSION}" >> $GITHUB_ENV
      #     # echo "VERSION=${RELEASE_VERSION/v/}" >> $GITHUB_ENV
      #     if [ -f ./release.md ]; then
      #       r=$(cat ./release.md)                             # <--- Read release.md (Provide correct path as per your repo)
      #       r="${r//'%'/'%25'}"                               # Multiline escape sequences for %
      #       r="${r//$'\n'/'%0A'}"                             # Multiline escape sequences for '\n'
      #       r="${r//$'\r'/'%0D'}"                             # Multiline escape sequences for '\r'
      #       echo "RELEASE_BODY=$r" >> $GITHUB_OUTPUT          # <--- Set environment variable
      #     else
      #       echo "RELEASE_BODY='Changelog of commits: [..${RELEASE_VERSION}](https://github.com/${GITHUB_REPOSITORY}/compare/...${RELEASE_VERSION})'" >> $GITHUB_OUTPUT
      #     fi

      - name: Release
        uses: softprops/action-gh-release@v2
        if: startsWith(github.ref, 'refs/tags/')
        with:
          generate_release_notes: true
          discussion_category_name: Announcements
          # # repo_token: ${{ secrets.GITHUB_TOKEN }}
          token: ${{ secrets.GITHUB_TOKEN }}
          # # tag: ${{ github.ref }}
          # tag_name: ${{ github.ref_name }}
          # name: ${{ env.TAG_NAME }}
          # # overwrite: true
          # overwrite_files: true
          # prerelease: true
          # draft: true
          # # file_glob: true
          append_body: true
          preserve_order: true
          # body_path: relnotes.md
          body: |
            This release was created by: ${{ github.event.sender.login }}
            Release of Azt-Go, built from commit ${{ env.SHORT_SHA }}, is now available.
          files: |
            ./azt-*.*
          # # body: |
          # #   ${{ steps.read_release.outputs.RELEASE_BODY }}
          # body: |
          #   ${{ steps.read_release_notes_0.outputs.RELEASE_BODY }}
          # body_path: ${{ github.workspace }}-CHANGELOG.txt
          # body_path: RELNOTES.md
          # files: |
          #   LICENSE
          #   RELNOTES.md
